"""empty message

Revision ID: 9b558d0aab4d
Revises: fc1e5681d928
Create Date: 2024-01-16 20:33:17.616282

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9b558d0aab4d'
down_revision = 'fc1e5681d928'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('avatars', schema=None) as batch_op:
        batch_op.add_column(sa.Column('avatar_name', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('avatars', schema=None) as batch_op:
        batch_op.drop_column('avatar_name')

    # ### end Alembic commands ###
